### ISSUE TITLE
Resource values are lost when adding a new resource

### ISSUE THREAD

**Issue by tcalmant** [eclipse/org.eclipse.sensinact.gateway#109]
When creating new resources calling `ModelNexus.handleDataUpdate()`, all the resources the service was already containing have their values removed (set to null).

I have added a [test](https://github.com/tcalmant/org.eclipse.sensinact.gateway/blob/thomas/value-bug/prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusTest.java#L242-L265) to show the error.

I suspect the issue comes from the [attribute version check](https://github.com/tcalmant/org.eclipse.sensinact.gateway/blob/thomas/value-bug/prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/emf/SensinactCopier.java#L47) in `SensinactCopier`

**Comment by tcalmant** [comment]
@juergen-albert, I might need some help as I don't understand the behaviour of EMF copy around there.
There seems to be an incorrect copy of the `eStorage` field of the `ProviderImpl` when calling the `SensinactCopier` when the service state is new in [ModelNexus.updateInstances()](https://github.com/tcalmant/org.eclipse.sensinact.gateway/blob/thomas/value-bug/prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java#L443)

**Comment by juergen-albert** [comment]
*facepalm* I see the issue. I'm on it.
