### ISSUE TITLE
Integration bndrun files aren't maintained properly

### ISSUE THREAD

**Issue by timothyjward** [eclipse/org.eclipse.sensinact.gateway#301]
The `bndrun` file is a difficult one because some of its content is "source" and some usually "generated". We have no choice but to check these files in, as without them it isn't possible to run the tests.

The issue that we have is that the CI build currently regenerates a portion of these files, rather than validating what's there. This leads to two main problems:

1. The executed content of the tests can change over time without any changes to the project source
2. The test "source" files can (and do) end up invalid, containing merge conflicts and other goop (e.g. [this test](https://github.com/eclipse/org.eclipse.sensinact.gateway/blame/d3a060038845d40e0fe2e852770058c9141279e0/southbound/history/timescale-provider/integration-test.bndrun#L71-L74))

I strongly recommend that we move from our current "Just let CI decide" to a more repeatable "CI does what it's told" model. This means that all bndrun files will be resolved by CI for validation, but fail if there are changes. We can introduce a build profile which will update the bndrun file(s) for local use by developers. This is similar to the way in which npm manages dependencies, where the package-lock.json file is regenerated in development builds, but not in CI. This will ensure that builds are more repeatable, and that there is more developer oversight of changes in bndrun files.

**Comment by timothyjward** [comment]
@juergen-albert @maho7791 @tcalmant @stbischof 

I will work on a PR which adds this in a minimally invasive way, and would welcome feedback on the approach

**Comment by stbischof** [comment]
Only idea that came in my mind with this is.

The bnd resolver and tester plugin could could be set to 'failOnChange'.
So we would be forced to non-generate bndrun. And habe them ass full source mode.

Thats not friendly for the Developer...
And dependeabot Version Updates will also fail directly

**Comment by timothyjward** [comment]
> Thats not friendly for the Developer...

Would you prefer it if the profiles were inverted, i.e. CI enables the profile to be strict, and normal development builds run as they are now?

> And dependeabot Version Updates will also fail directly

That's something that would need to be fixed in dependabot itself. The flow could be fairly quick though:

    git fetch origin <dependabot branch>
    git checkout <dependabot branch>
    mvn -P dependabot verify
    git add -u
    git commit --amend
    git push origin

**Comment by stbischof** [comment]
dependabot way LGTM!

And reproducable build over developer happiness.

**Comment by juergen-albert** [comment]
I'd like to rediscuss this, as the check seems to strict, as it seems to fail if the order is not correct. This will always be the case, if something changes and if I have resolved it again. On save the result gets merged into the existing runbundles instruction. This means changes are appended at the end. 

I have to delete the -runbundles and then have to resolve every single bndrun, or is there a way to resolve and overwrite the existing runbundles?

**Comment by juergen-albert** [comment]
And my machine seems to produce a different order then what the build on github arrives at...

**Comment by timothyjward** [comment]
> I'd like to rediscuss this, as the check seems to strict, as it seems to fail if the order is not correct. This will always be the case, if something changes and if I have resolved it again.

This should not be the case. We sort all the runbundles by symbolic name for exactly this reason. 
https://github.com/eclipse/org.eclipse.sensinact.gateway/blob/7b9bcd99c2b5859b733ed78b73f989fe4bfa0c57/core/impl/integration-test.bndrun#L15

At a guess you have missed this from a new bndrun?

> I have to delete the -runbundles and then have to resolve every single bndrun, or is there a way to resolve and overwrite the existing runbundles?

    mvn -P dependabot clean verify

will rebuild and resolve every bndrun. It takes 60-90 seconds on my machine.

**Comment by timothyjward** [comment]
We're now using the `verify` goal of `bnd-resolver-maven-plugin` which enforces good behaviour in CI without being so picky about the resolution result. See Pull Request #335
