### ISSUE TITLE
Bump spifly from v1.3.6 to v1.3.7

### ISSUE THREAD

**Issue by dleangen** [eclipse/org.eclipse.sensinact.gateway#306]
I was having some build issues, and bumping the version of spifly from the 1.3.6 to 1.3.7 fixed that.

**Comment by dleangen** [comment]
Had some issues because the author and committer emails did not match the email used to sign the ECF, but it's all good now.

**Comment by timothyjward** [comment]
> Had some issues because the author and committer emails did not match the email used to sign the ECF

Perhaps we need to add a `CONTRIBUTING.MD` to the repo including this warning.

**Comment by dleangen** [comment]
@timothyjward Yup, I will be taking your email and inserting that into the updated docs. 👍
