### ISSUE TITLE
Handle common implementation types

### ISSUE THREAD

**Issue by timothyjward** [eclipse/org.eclipse.sensinact.gateway#313]
Seen in sensiNact logs:
> 2024-01-17 14:39:19 [Thread-2] WARN org.eclipse.sensinact.core.model.nexus.emf.EMFUtil - The class class java.util.ArrayList has no matching EClassifier. Creating an anonymous EDataType
2024-01-17 14:39:18 [Thread-2] WARN org.eclipse.sensinact.core.model.nexus.emf.EMFUtil - The class class java.util.LinkedHashMap has no matching EClassifier. Creating an anonymous EDataType

We should be able to handle this more gracefully

**Comment by juergen-albert** [comment]
What leads to that message?

**Comment by timothyjward** [comment]
Attempting to push an update using `GenericDto` with the type set to `java.util.ArrayList.class` or `java.util.LinkedHashMap.class`

**Comment by juergen-albert** [comment]
Hmmm.. okay. I haven't considered multi valued attributes yet. Can you create a testcase in a branch, so I can implement that?

**Comment by timothyjward** [comment]
Test cases available in timothyjward@c6aacb8e7e3c798fa059de7d16726523167b0537

They cover a range of inputs and expect immutable ordered copies to be returned. We don't have to keep the implementation type though (copying a custom comparator for a SortedSet is a non-starter) as long as we don't mess up the order.
