### ISSUE TITLE
Sensorethings via MQTT with existing MQTT Connection

### ISSUE THREAD

**Issue by juergen-albert** [eclipse/org.eclipse.sensinact.gateway#389]
Currently the MQTT addon for Sensorethings starts it own MQTT Server. This is convenient, but we should also provide a Version, that can use an existing MQTT Server.

**Comment by timothyjward** [comment]
> Currently the MQTT addon for Sensorethings starts it own MQTT Server. This is convenient, but we should also provide a Version, that can use an existing MQTT Server.

This is not possible. The entire specification is predicated on being able to see which topics a listener is registered to. This is not possible as part of the MQTT standards, and requires a provider-specific hook in implementations which do support it. In the case of Moquette this is a callback interface registered with the broker when it starts.

**Comment by juergen-albert** [comment]
Ah, okay. I wasn't aware of that part. Instead of using MQTT we might want to think about live data updates via SSE or Websockets.

**Comment by timothyjward** [comment]
Given that it isn't possible to achieve, can we close this issue?
