### ISSUE TITLE
replace org.eclipse.sensinact.gateway.northbound.sensorthings.dto with EMF Model

### ISSUE THREAD

**Issue by juergen-albert** [eclipse/org.eclipse.sensinact.gateway#401]
For better reusability it would be great if we could replace the DTOs with an EMF Model

**Comment by timothyjward** [comment]
I don't understand the purpose of this. The sensor things DTOs are just simple object mappings of the JSON from the specification. It feels like a negative step to start imbuing them with additional powers.
